### PR TITLE
[#226] Change error message formatting

### LINKED ISSUE #226: Revise styling of the output
# Clarification and motivation

Look at the [readme](https://github.com/serokell/xrefcheck#readme), at how the output looks like.

This is all subjective, but there are things that feel like a bad design of the style:
* Names of bad files are given in gray, and they should on contrary stand out.
* Those `-` before `text`, `link`, and `anchor` look redundant, especially after #202.

Let's discuss all this and apply some fixes before the release.

# Acceptance criteria
* Some feedback on the styling is gathered.
* Concrens are discussed.
* On concerns we agreed upon - adjustements in the code are made.

### PR DESCRIPTION
**Pull request by int-index**
## Description

**Problem:** multiple issues with the CLI output

1. In the `--help` output, metavars `GLOB_PATTERN` and `REPOSITORY_TYPE` used spaces instead of underscores. Variables typically don't contain spaces in their names, so it looked confusing.
2. Incorrect or unintuitive coloring of the output. For example, filenames were dim even though they're important and should stand out, the report of success wasn't green, error messages weren't red, etc.
3. Excessive indentation and empty lines that made it difficult to visually parse the error report. Also the use of the exotic `➥` character that looks bad in many font configurations.
4. Filenames and line numbers were far apart, making it impossible to Ctrl+Click to jump to the source of the error.
5. In case of connection failure, the output was too verbose and platform-dependent.

**Solution:**
1. Include the filename in positions returned by the scanner.
2. Adjust the pretty-printing functions and update test output.
3. Extend `VerifyError` with a constructor for connection failures.

## Related issue(s)

Fixes #226.

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](https://github.com/serokell/xrefcheck/tree/master/README.md)
    - Haddock

- Public contracts
  - [x] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [x] I added an entry to the [changelog](https://github.com/serokell/xrefcheck/tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](https://github.com/serokell/style/blob/master/haskell.md).

#### ✓ Release Checklist

- [ ] I updated the version number in `package.yaml`.
- [ ] I updated the [changelog](https://github.com/serokell/xrefcheck/tree/master/CHANGES.md) and moved everything
      under the "Unreleased" section to a new section for this release version.
- [ ] (After merging) I edited the [auto-release](https://github.com/serokell/xrefcheck/releases/tag/auto-release).
    * Change the tag and title using the format `vX.Y.Z`.
    * Write a summary of all user-facing changes.
    * Deselect the "This is a pre-release" checkbox at the bottom.
- [ ] (After merging) I updated [`xrefcheck-action`](https://github.com/serokell/xrefcheck-action#updating-supported-versions).
- [ ] (After merging) I uploaded the package to [hackage](https://hackage.haskell.org/package/xrefcheck).

### CODE REVIEW

**Comment by Martoon-00** [comment]
Looks good, I see why these changes are reasonable and agree.

One concern: after merging error message for every single reference into one block, discrepancies in indentation became more apparent:

* The difference in leading `-` being present at one line and being absent at another. Maybe we can remove this `-` in lists after all. (Clearly the last line is not a list, but the difference still stands out)

```
check-images.md:20:1-34: bad reference:
  The reference to "bad image ref 3" failed verification.
  - link (relative): ./3.png      <------
  File does not exist:
    ./3.png                               <------
```

* Indentation size here:

```
The reference to "Reference lowered" failed verification.
  - anchor (file-local): uppercase-name
  Anchor 'uppercase-name' is not present, did you mean:
      - UPPERCASE-NAME (handmade) 14:3-27
```

Maybe these are worth changing to look uniform. WDYT?

**Comment by int-index** [comment]
Agreed, I'll try to change the phrasing further to avoid this issue.

**Comment by int-index** [comment]
I've pushed a change, @Martoon-00 would you be so kind to take another look?

This time indentation should be consistent. Also I've modified the scanner so that all positions include the filename.

**Comment by Martoon-00** [comment]
My apologies for coming late.

Looks much better as to me, thanks for addressing my concern.

**Comment by Martoon-00** [comment]
I have another minor issue:

```
check-ignoreExternalRefsTo.md:7:10-53: bad reference:
  The reference to "web-site" failed verification.
  Connection failure
  when processing an external link: https://localhost:20000/web-site
```

Commonly used links are longer, and likely the last line won't fit into the default terminal size of 80 characters width. If most of the links get wrapped, that may look ugly. For this reason, previously I tried to keep links in their own line; would it make sense here?

Ofc some links will wrap in either case, but, arguably, they'd still look prettier when start from their own line.

**Comment by int-index** [comment]
> Commonly used links are longer, and likely the last line won't fit into the default terminal size of 80 characters width. If most of the links get wrapped, that may look ugly. For this reason, previously I tried to keep links in their own line; would it make sense here?

Good point, I moved the link to its own line.

**Pull request merged**
