### PR TITLE
[#140] Unknown field errors

### LINKED ISSUE #140: Fail parsing when config contains unknown keys
# Clarification and motivation

At the moment, if the config file contains an unexpected key, the parser will simply ignore it.

However, I would argue the config parser should fail if it finds an unexpected key. E.g., if the user accidentally writes `ignore` instead of `ignored`, we don't want xrefcheck to silently ignore that field and carry on. We want it to exit and tell the user about this issue.

Similarly, the CLI parser will also (correctly) fail when it finds an option it doesn't expect.

# Acceptance criteria

* Xrefcheck fails when it parses an unknown config key.
* Xrefcheck prints a user-friendly error message.

### PR DESCRIPTION
**Pull request by Sorokin-Anton**
## Description

Problem: As in #140, unrecognised fields of config are ignored. We want to raise an error instead

Solution: change aeson options for config and it's subtypes, now it throws errors like
```
xrefcheck: Aeson exception:
Error in $: Unknown fields: ["traversajhl"]
```

## Related issue(s)

Fixes #140

## :white_check_mark: Checklist for your Pull Request

Ideally a PR has all of the checkmarks set.

If something in this list is irrelevant to your PR, you should still set this
checkmark indicating that you are sure it is dealt with (be that by irrelevance).

#### Related changes (conditional)

- Tests
  - [x] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](/README.md)
    - Haddock

- Public contracts
  - [x] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [ ] I added an entry to the [changelog](/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](/docs/code-style.md).

### CODE REVIEW

**Review by dcastro — APPROVED** [review]
LGTM :+1:

**Review by dcastro — CHANGES_REQUESTED** [review]
Actually, forget what I said, don't merge yet, not until 0.2.1 is released ^^ I'm temporarily revoking my approval to block merging.

**Review by dcastro — APPROVED** [review]

**Comment by dcastro** [comment]
We can merge this PR now ^^

**Comment by Sorokin-Anton** [comment]
@Sereja313 on CI I discovered that there is unknown field in one of our tests, can you fix this?

**Pull request merged**
